apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-testdevops
spec:
  selector:
    matchLabels:
      app: k8s-testdevops
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-testdevops
    spec:
      containers:
      - name: k8s-testdevops
        image: danhorma/testdevops:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8000
