apiVersion: v1
kind: Service
metadata:
  name: k8s-testdevops
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: http
    port: 8000
    targetPort: 8080
  selector:
      app: k8s-testdevops
      